# https://docs.haskellstack.org/en/stable/travis_ci/
# https://nixos.wiki/wiki/Nix_on_Travis
language: nix
cache:
  directories:
  - $HOME/nix.store

os: linux
dist: bionic

env:
  - PACKAGE=atlas
  - PACKAGE=bidi-icu
  - PACKAGE=common
  - PACKAGE=const
  - PACKAGE=engine
  - PACKAGE=fontconfig
  - PACKAGE=freetype
  - PACKAGE=glow
  - PACKAGE=harfbuzz
  - PACKAGE=hkd
  - PACKAGE=language-server
  - PACKAGE=parsnip
  - PACKAGE=primitive-extras
  - PACKAGE=primitive-ffi
  - PACKAGE=ptrdiff
  - PACKAGE=smawk
  - PACKAGE=tabulation-hash
  - PACKAGE=ui
  - PACKAGE=watch
  - PACKAGE=watch-directory
  - PACKAGE=weak

before_install:
  - sudo mkdir -p /etc/nix
  - echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
  - echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
  - nix-env -iA nixpkgs.ghc nixpkgs.cabal-install

before_cache:
  - mkdir -p $HOME/nix.store
  - nix copy --to file://$HOME/nix.store -f default.nix buildInputs

before_script:
  - sudo mkdir -p /etc/nix && echo 'sandbox = true' | sudo tee /etc/nix/nix.conf

script:
  - cabal update
  - nix-build shell.nix
  - cabal --project=nix-shell-cabal.project build --only-dependencies $PACKAGE
  # - cabal --project=nix-shell-cabal.project test --only-dependencies $PACKAGE
  # - cabal --project=nix-shell-cabal.project test $PACKAGE
